drop table if exists bet cascade;
drop table if exists player_stats cascade;
drop table if exists game cascade;
drop table if exists weather cascade;
drop table if exists contract cascade;
drop table if exists club_to_tournament cascade;
drop table if exists tournament cascade;
drop table if exists league cascade;
drop table if exists club cascade;
drop table if exists referee cascade;
drop table if exists coach cascade;
drop table if exists player cascade;
drop table if exists nationality cascade;
drop table if exists nation cascade;
drop table if exists person cascade;

drop table if exists person cascade;
create table person (
    person_id bigint generated by default as identity primary key,
    full_name varchar(100) not null,
    birth_dt date not null
);

drop table if exists nation cascade;
create table nation (
    nation_id bigint generated by default as identity primary key,
    country varchar(80) not null unique
);

drop table if exists nationality cascade;
create table nationality (
    person_id bigint not null,
    nation_id bigint not null,
    primary key (person_id, nation_id),
    foreign key (person_id) references person(person_id) on delete cascade,
    foreign key (nation_id) references nation(nation_id) on delete cascade
);

drop table if exists player cascade;
create table player (
    person_id bigint primary key,
    nick varchar(50),
    working_foot varchar(10) not null,
    is_finished boolean not null default false,
    role varchar(30) not null,
    foreign key (person_id) references person(person_id) on delete cascade,
    check (working_foot in ('left', 'right', 'both')),
    check (role in ('goalkeeper', 'defender', 'midfielder', 'forward'))
);

drop table if exists coach cascade;
create table coach (
    person_id bigint primary key,
    license varchar(30) not null,
    foreign key (person_id) references person(person_id) on delete cascade,
    check (license in ('A', 'B', 'Pro', 'UEFA A', 'UEFA B', 'UEFA Pro'))
);

drop table if exists referee cascade;
create table referee (
    person_id bigint primary key,
    category varchar(30) not null,
    foreign key (person_id) references person(person_id) on delete cascade,
    check (category in ('regional', 'national', 'fifa'))
);

drop table if exists club cascade;
create table club (
    club_id bigint generated by default as identity primary key,
    club_name varchar(100) not null unique,
    main_stadium varchar(100) not null,
    city varchar(80) not null
);

drop table if exists league cascade;
create table league (
    league_id bigint generated by default as identity primary key,
    nation_id bigint not null,
    league_name varchar(100) not null,
    foreign key (nation_id) references nation(nation_id) on delete restrict,
    unique (nation_id, league_name)
);

drop table if exists tournament cascade;
create table tournament (
    tournament_id bigint generated by default as identity primary key,
    league_id bigint not null,
    start_year integer not null,
    foreign key (league_id) references league(league_id) on delete restrict,
    unique (league_id, start_year),
    check (start_year between 1950 and 2050)
);

drop table if exists club_to_tournament cascade;
create table club_to_tournament (
    club_id bigint not null,
    tournament_id bigint not null,
    primary key (club_id, tournament_id),
    foreign key (club_id) references club(club_id) on delete cascade,
    foreign key (tournament_id) references tournament(tournament_id) on delete cascade
);

drop table if exists weather cascade;
create table weather (
    weather_id bigint generated by default as identity primary key,
    temperature numeric(4,1) not null,
    wind_speed numeric(4,1) not null,
    weather_type varchar(30) not null,
    humidity integer not null,
    check (humidity between 0 and 100),
    check (weather_type in ('sunny', 'cloudy', 'rainy', 'snowy', 'foggy', 'windy'))
);

drop table if exists contract cascade;
create table contract (
    start_dt date not null,
    person_id bigint not null,
    club_id bigint not null,
    end_dt date,
    week_salary numeric(12,2) not null,
    primary key (start_dt, person_id, club_id),
    foreign key (person_id) references person(person_id) on delete cascade,
    foreign key (club_id) references club(club_id) on delete cascade,
    check (week_salary >= 0),
    check (end_dt is null or end_dt >= start_dt)
);

drop table if exists game cascade;
create table game (
    game_id bigint generated by default as identity primary key,
    main_ref_id bigint not null,
    away_club bigint not null,
    home_club bigint not null,
    tournament_id bigint not null,
    game_dt timestamp not null,
    weather_id bigint,
    home_goals integer not null default 0,
    away_goals integer not null default 0,
    foreign key (main_ref_id) references referee(person_id) on delete restrict,
    foreign key (away_club) references club(club_id) on delete restrict,
    foreign key (home_club) references club(club_id) on delete restrict,
    foreign key (tournament_id) references tournament(tournament_id) on delete restrict,
    foreign key (weather_id) references weather(weather_id) on delete set null,
    check (home_club <> away_club),
    check (home_goals >= 0),
    check (away_goals >= 0)
);

drop table if exists player_stats cascade;
create table player_stats (
    game_id bigint not null,
    player_id bigint not null,
    position varchar(10) not null,
    sub_on integer,
    sub_off integer,
    red_card boolean not null default false,
    yellow_card integer not null default 0,
    assist integer not null default 0,
    goal integer not null default 0,
    primary key (game_id, player_id),
    foreign key (game_id) references game(game_id) on delete cascade,
    foreign key (player_id) references player(person_id) on delete cascade,
    check (position in (
        'GK',
        'CB',
        'LB',
        'RB',
        'LWB',
        'RWB',
        'CDM',
        'CM',
        'CAM',
        'LM',
        'RM',
        'LW',
        'RW',
        'CF',
        'ST'
    )),
    check (sub_on is null or sub_on between 0 and 130),
    check (sub_off is null or sub_off between 0 and 130),
    check (sub_on is null or sub_off is null or sub_off >= sub_on),
    check (yellow_card between 0 and 2),
    check (assist >= 0),
    check (goal >= 0)
);

drop table if exists bet cascade;
create table bet (
    bet_id bigint generated by default as identity primary key,
    game_id bigint not null,
    type_of_bet varchar(50) not null,
    coef_yes numeric(6,2) not null,
    coef_no numeric(6,2) not null,
    foreign key (game_id) references game(game_id) on delete cascade,
    check (coef_yes > 1),
    check (coef_no > 1),
    check (type_of_bet in (
        'total_2.5',
        'both_to_score'
    ))
);
